### ISSUE TITLE
Issue with Json Rpc

### ISSUE THREAD

**Issue by aliabbas572** [qwertycoin-org/qwertycoin#4]
When ever I use simplewallet and try to call it from my web browser and check its details I get this error:

{"error": {"code" : -32700 , "message" : "Parse error"} , "jsonrpc" : "2.0"}

Kindly help me to resolve this.

**Comment by qwertycoin-org** [comment]
Hi,

yeah it was an issue with RPC-Server. We fixed this Issue now! Please update your Daemon and-/or all Wallets (including GUI Version).

**Comment by aliabbas572** [comment]
I have done that but still not resolved. Basically i'm trying to make a clone of your faucet but when i use your simple wallet with the given commands and put all my files into folder the issue is that the json rpc gives an error and as it is not available the script does not see it working and the whole webpage does not work only shows your logo and all the field are showing. whereas if i remove the http://127.0.0.1:18070/json-rpc thing script from index.php then it starts to show up the page but still it can not work with the website. Any resolutions

**Comment by qwertycoin-org** [comment]
Ah okay. You cant check your Balance through your Browser, simply by open IP:port/json_rpc. You must use CURL or any other JSON based Parser. You start the Daemon and Simplewallet as defined? With bind IP and Port. Alternative: try an other Port.

**Comment by aliabbas572** [comment]
thanks just sent some regards to your faucet too. I mean just sent some QWC to your faucet 👍
